using System;
using System.Diagnostics;
using System.Linq;

public class RandomStringGenerator 
{
    private static readonly Random random = new Random();
    private const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    public string randomString;
    public string randomStringHero;

    static string[] nameFirst = {
        "Anh Hùng",
        "Huyền Thoại",
        "Ninja",
        "Bậc Thầy",
        "Hiệp Khách",
        "Kiếm Sĩ",
        "Đấu Sĩ",
        "Bảo Vệ",
        "Nhà Chiến",
        "Thủ Lĩnh",
        "Binh Sĩ",
        "Quân Sĩ",
        "Quyền Thủ",
        "Võ Sĩ",
        "Đại Đao",
        "Thợ Săn",
        "Thợ Rèn",
        "Phi Hổ",
        "Thần Kiếm",
        "Bá Vương",
        "Thánh Chiến",
        "Trượng Phu",
        "Bậc Thầy",
        "Thánh Tướng",
        "Anh Tài",
        "Thần Sức",
        "Thần Đao",
        "Nữ Tướng",
        "Hiệp Tướng",
        "Chiến Giả",
        "Đấu Trường",
        "Tử Sĩ",
        "Đại Lão",
        "Quán Chiến",
        "Phù Thủy",
        "Thần Tốc",
        "Dũng Tướng",
        "Kỵ Sĩ",
        "Thần Kỵ",
        "Binh Nghĩa",
        "Thủ Tướng",
        "Cao Thủ",
        "Võ Lâm",
        "Kiện Tướng",
        "Hiệp Hiệu",
        "Binh Thần",
        "Thánh Hiệp",
        "Hiệp Binh",
        "Phòng Thủ",
        "Đấu Pháp",
        "Thần Thanh",
        "Kỵ Binh",
        "Thái Sư"
    };


    public static string[] nameHero =
    {
        "Son Goku",
        "Naruto Uzumaki",
        "Monkey D. Luffy",
        "Ichigo Kurosaki",
        "Goku Black",
        "Vegeta",
        "Saitama",
        "Eren Yeager",
        "Light Yagami",
        "Lelouch Lamperouge",
        "Natsu Dragneel",
        "Edward Elric",
        "Sasuke Uchiha",
        "Gon Freecss",
        "Killua Zoldyck",
        "Roronoa Zoro",
        "Gohan",
        "Kakashi Hatake",
        "Levi Ackerman",
        "Meliodas",
        "L",
        "Yusuke Urameshi",
        "Yugi Mutou",
        "Spike Spiegel",
        "Ken Kaneki",
        "Tanjiro Kamado",
        "Rukia Kuchiki",
        "Broly",
        "Grimmjow Jaegerjaquez",
        "Gintoki Sakata",
        "Alucard",
        "Naruto",
        "Luffy",
        "Sakura Haruno",
        "Ryuk",
        "Asuna Yuuki",
        "Shoto Todoroki",
        "Mikasa Ackerman",
        "Erza Scarlet",
        "Goku",
        "Sanji Vinsmoke",
        "Shinji Ikari",
        "Saber",
        "Vegeta",
        "Itachi Uchiha",
        "Sasuke",
        "Gaara",
        "Kurama",
        "Jotaro Kujo",
        "Shinichi Kudo",
        "Kenshin Himura",
        "Kamina",
        "Hiei",
        "Inuyasha",
        "Sasori",
        "Shanks",
        "Eren",
        "Gohan",
        "Naruto",
        "Lelouch",
        "Edward Elric",
        "Tsunade",
        "Hinata Hyuga",
        "Madara Uchiha",
        "Kisame Hoshigaki",
        "Gon",
        "Killua",
        "Meruem",
        "Zeref",
        "Zeno Zoldyck",
        "Guts",
        "Kirito",
        "Eikichi Onizuka",
        "Mugen",
        "Makoto Naegi",
        "Mikoto Misaka",
        "Tetsuo Shima",
        "Kaneda",
        "Simon",
        "Lelouch Lamperouge",
        "Ryuk",
        "Eren Yeager",
        "Shigeo Kageyama",
        "All Might",
        "Yusuke Urameshi",
        "Shoyo Hinata",
        "Naruto",
        "Saitama",
        "Spike Spiegel",
        "Soma Yukihira",
        "Koro-sensei",
        "Vash the Stampede",
        "Monkey D. Luffy",
        "Mikasa Ackerman",
        "Sanji",
        "Tetsuo Shima",
        "Kaneda",
        "Spider-Man",

        "Batman",
        "Superman",
        "Iron Man",
        "Wonder Woman",
        "Captain America",
        "Thor",
        "The Flash",
        "Hulk",
        "Green Lantern",
        "Black Widow",
        "Aquaman",
        "Wolverine",
        "Deadpool",
        "Doctor Strange",
        "Green Arrow",
        "Black Panther",
        "Cyborg",
        "Captain Marvel",
        "Hawkeye",
        "Ant-Man",
        "Daredevil",
        "Nightwing",
        "Harley Quinn",
        "Luke Cage",
        "Jessica Jones",
        "Storm",
        "Beast",
        "Catwoman",
        "Jean Grey",
        "Magneto",
        "Vision",
        "Rogue",
        "Gambit",
        "Colossus",
        "Cyclops",
        "Mr. Fantastic",
        "Invisible Woman",
        "Human Torch",
        "Thing",
        "Scarlet Witch",
        "Quicksilver",
        "Loki",
        "Black Canary",
        "Bane",
        "Deadshot",
        "Robin",
        "Supergirl",
        "The Joker",
        "Punisher",
        "Lex Luthor",
        "Thanos",
        "Darkseid",
        "Riddler",
        "Dr. Doom",
        "Harley Quinn",
        "Juggernaut",
        "Professor X",
        "Apocalypse",
        "Black Adam",
        "Doctor Octopus",
        "Deathstroke",
        "Venom",
        "Mystique",
        "Red Hood",
        "Carnage",
        "Star-Lord",
        "Gamora",
        "Rocket Raccoon",
        "Groot",
        "Drax the Destroyer",
        "Black Bolt",
        "Medusa",
        "Wolverine",
        "Storm",
        "Professor X",
        "Cable",
        "Phoenix",
        "Magneto",
        "Apocalypse",
        "Mystique",
        "Sabretooth",
        "Emma Frost",
        "Silver Surfer",
        "Galactus",
        "Nick Fury",
        "Green Goblin",
        "Norman Osborn",
        "Sandman",
        "Rhino",
        "Electro",
        "Vulture",
        "Kingpin",
        "Hawkeye",
        "Hank Pym",
        "Wasp",
        "Vision",
        "Scarlet Witch",
        "Black Widow"
    };

    // ramdom tên nhân vật
    public static string GenerateRandomName()
    {
        string first = nameFirst[random.Next(nameFirst.Length)];
        string hero = nameHero[random.Next(nameHero.Length)];
        return $"{first} {hero}";
    }

    // ramdom chuỗi ký tự
    public static string GenerateRandomString(int length)
    {
        if (length <= 0 || length > chars.Length)
        {
            throw new ArgumentOutOfRangeException("length", "Length must be greater than 0 and less than or equal to " + chars.Length);
        }

        return new string(Enumerable.Repeat(chars, length)
            .Select(s => s[random.Next(s.Length)])
            .ToArray());
    }
}
